[package]
name = "file_crypto_base64"
version = "1.5.4"
authors = ["ItiharaYuuko"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = ""